services:
  player-db:
    image: postgres:16-alpine
    container_name: player-db
    environment:
      POSTGRES_DB: player_service
      POSTGRES_USER: player_service
      POSTGRES_PASSWORD: player_service
    ports:
      - "5432:5432"
    volumes:
      - player-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U player_service"]
      interval: 5s
      timeout: 3s
      retries: 5

  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_store_service
      POSTGRES_USER: inventory_store_service
      POSTGRES_PASSWORD: inventory_store_service
    ports:
      - "5433:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_store_service"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  player-db-data:
  inventory-db-data: